server:
  port: 8088

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/shoppingmall?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB
      #enable: true
      #location: /Users/YoungminKim
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379

logging:
  level:
    com.shoppingmall: INFO

mybatis:
  type-aliases-package: com.shoppingmall.vo, com.shoppingmall.dto.request
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    lazy-load-trigger-methods: ''
  type-handlers-package: com.shoppingmall.handler

os:
  window:
    upload-path: C:/shoppingmall/upload/
  mac:
    upload-path: /Users/youngminkim/projects/shoppingmall/upload/
  linux:
    upload-path: /var/www/shoppingmall/upload/

email:
  title: "쇼핑몰 인증 번호 입니다."

jwt:
  secret:
    key: 4oCYc3ByaW5nYm9vdC1zaG9wcGluZy1tYWxsLWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXTigJkK