server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/shoppingmall?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      #enable: true
      #location: /Users/YoungminKim
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.springframework.web: DEBUG
    com.shoppingmall: DEBUG

mybatis:
  type-aliases-package: com.post.domain
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

os:
  window:
    upload-path: C:/shoppingmall/upload/
  mac:
    upload-path: /Users/youngminkim/projects/shoppingmall/upload/
  linux:
    upload-path: /var/www/shoppingmall/upload/

email:
  title: "쇼핑몰 인증 번호 입니다."